services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/pcrdb
    depends_on:
      - postgres
      - redis
    ports:
      - "8082:8082"
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: pcrdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
  # WARNING - see HRDS's readme.md for running mssql on macOS with Apple silicon
  sqledge:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ngPassword!"
  servicebus:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "./service-bus-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Str0ngPassword!"
      ACCEPT_EULA: "Y"
      SQL_WAIT_INTERVAL: 60
    depends_on:
      - sqledge
